### ISSUE TITLE
Can't open program after upgrade to 2.7.1

### ISSUE THREAD

**Issue by PAKoffee** [bardsoftware/ganttproject#1159]
Company only allows admin access for 50 minutes to update software.  New version of 2.7.1 will not start unless admin rights are available.  Is there a way to install/update software so that admin rights are not needed to use the program?

**Comment by dbarashev** [comment]
Answering to the question, you may try ZIP distro. See the instructions: https://github.com/bardsoftware/ganttproject/wiki/Installing-from-ZIP

However I really doubt that 2.7.1 per se is the issue because there were no significant changes in the installer. I don't know how does is work on Windows system (I guess you're on Windows), but as far as I remember it was possible to install programs for current user and for all users. If you installed GP from Admin account for the current user only then only Admin can use it.
