### ISSUE TITLE
Sort tasks in the table by begin/end date

### ISSUE THREAD

**Issue by rmasci** [bardsoftware/ganttproject#1216]
It would be nice to be able to sort the chart by:
- Start Date
- End Date
- Alphabetically
- Duration

Thanks for a wonderful product.

**Comment by dbarashev** [comment]
What's the purpose of sorting?
See this comment which explains the question: https://github.com/bardsoftware/ganttproject/issues/595#issuecomment-116271949

**Comment by rmasci** [comment]
When you add tasks in, they'll be ordered in the order you put them in.
Normally I want to view it in order of start date, so my chart moves from
left to right, top to bottom.  To do this today I have to manually move
them around. I could also want to list these tasks alphabetically, or by
the end date.

**Comment by dbarashev** [comment]
Okay, sorting sibling tasks by start date so that tasks are read left to right, top to bottom is understood. I stressed "sibling" because we can talk only about this partial order without breaking the tree. Tasks from different tree branches can't be compared this way.

What is the purpose of sorting by name? If the goal is to find a task then you can use search feature. Hit Ctrl+F.
