### ISSUE TITLE
Progress % on Gantt chart task does not scale correctly

### ISSUE THREAD

**Issue by Oneirohero** [bardsoftware/ganttproject#1218]
The black bar on the Gantt chart bars meant to indicate progress percentage scales to the width of the screen from left to right instead of to the bar, meaning when you scroll along the actual size of the progress % changes without having changed the length of the task nor the progression % value.

For it to be a useful indication, a change must be made to make the black progress % scale to the task itself and for it to be a fixed position regardless of how you scroll left and right along the timeline, so that progression % can be accurately used as a 'ahead of time/on time/behind schedule' indicator.

Version: 2.7.2 Ostrava (build 1954)

Additional Observations: The bug seems to occur whenever the task bar is wider than the screen itself. As testing with a bar with a zoom level that allows it to fit within the screen width produces a fixed progress % as required. So in short, the bug occurs only when the bar is wider than the screen or goes off screen part way.

**Comment by dbarashev** [comment]
One more observation: this issue is reproducible exactly as described (scales to the width of the screen from left to right) only when project has no weekend days. When there are weekend days it is reproducible but in very restricted way (progress bar shows a little bit from the left side when it actually supposed to be outside of the viewport)
