### ISSUE TITLE
i cant edit my task 

### ISSUE THREAD

**Issue by jameskyeba** [bardsoftware/ganttproject#1251]
am using the trial version of the application but i wont let me edit the name of my task

**Comment by dbarashev** [comment]
1. There is no trial version of GanttProject
2. Task names are editable without any magic, both in the task table and in the task properties dialog.
3. If you really use GanttProject and really can't edit task names, please record a screencast which shows the problem. I am asking about the screencast because this issue is so impossible that it is easier to prove it with video rather than with text.

**Comment by dbarashev** [comment]
No response, closing
