### ISSUE TITLE
Progress bar not behaving intuitively [Feature request]

### ISSUE THREAD

**Issue by papa-chrimbo** [bardsoftware/ganttproject#1303]
Hi,

I think it would make sense to have an option to keep the progress bar static, and not scale to only the visible section of a given task. 

Example: if I have a task that is 50 days long and 10% complete, I would like the progress bar to cover the first 5 days even if I am zoomed in to the first week.

Please consider my request and thank you for working on this program.

**Comment by dbarashev** [comment]
I am not sure that I fully understand the request, but I think that in the latest GanttProject 2.8.1 progress works exactly the way you described. If task is 50 days long and is 10% complete then progress bar will always spread from the task start to task start + 5 days, no matter what zooming and panning is.

This used to be different in GP 2.7 due to a bug (see issue #1218)

**Comment by papa-chrimbo** [comment]
My program was not up to date, my sincere apologies
