### ISSUE TITLE
Failed to import microsoft project 2003 file with Greek encoding

### ISSUE THREAD

**Issue by nikospoulos** [bardsoftware/ganttproject#1331]
I am trying to import an mpp file (Msoft Project 2003) but is impossible.
Gant is 2.8.1 but also with 2.7.2 was not also impossible.

Something went wrong 

Failed to read input file=F:\ETGNPS ..... Unsupported encoding command ansicpg1253

**Comment by dbarashev** [comment]
This seems to be an issue in the third-party library which we use for parsing Microsoft Project files. Can you share a sample project file so that we were able to report this bug to the library authors?

**Comment by nikospoulos** [comment]
Ηι,
Sorry for the delay in answering.
All timeplans we have are private and i can not share. I asked yo send me
an example but this can be opened with warnings. Maybe the file length is
the problem. We have mpp covering years and are a bit long.attached the
small to see the warnings. Snother issue is that Gantt fills a lot the TEMP
DI of windows (appl-local). The issue is that when the program is closed
some temp.Gantt files remain.
Tnks/nikos

Στις 25 Ιαν 2017 4:39 μμ, ο χρήστης "Dmitry Barashev" <
notifications@github.com> έγραψε:

**Comment by dbarashev** [comment]
I can't say that I have understood everything, e.g. this phrase looks mysterious, because you didn't ask me anything

> I asked yo send me an example but this can be opened with warnings

If you can send a file by email (we will not publish  it) please use contact@ganttproject.biz

If you meant to send something attached to your reply (as I can guess from the phrase "attached the
small to see the warnings") then please attach it in GitHub interface. GitHub doesn't support email attachments.

Thanks.
