### ISSUE TITLE
error when importing form msproject, task date change

### ISSUE THREAD

**Issue by pawel-kwa** [bardsoftware/ganttproject#1339]
Hi,
I got this error when importing from msproject.

Warning 

The following problems were detected during import. Please note that some of them may be harmless

Severity
Message
INFO
Task with id=24 is blank task. Skipped
INFO
Some tasks (3 out of 29) have changed their start dates. See the details below.  What does it mean?
WARNING
Task Module 2 (Paderborn): was 4/2/17 12:00 AM, now 4/3/17 12:00 AM
WARNING
Task Module 3 (Cambridge): was 6/18/17 12:00 AM, now 6/19/17 12:00 AM
WARNING
Task Final Project Presentation: was 6/19/17 12:00 AM, now 5/9/17 12:00 AM
This report has been written to the log file. If you send it to GanttProject developers, please attach your MS project file
View log

[ganttproject-20170204193004.log.txt](https://github.com/bardsoftware/ganttproject/files/752493/ganttproject-20170204193004.log.txt)

**Comment by dbarashev** [comment]
When GanttProject imports files from MS Project it may reschedule some of the tasks and there is always a reason for that. The changes are reported, so that user was aware, however, normally it is a warning and not an error, provided that you understand the reasons why GanttProject changed the dates. This may mean that project calendar in GP is different from the one in MS Project (e.g. weekends are different) or that GanttProject scheduler enforced some constraints which MS Project decided to ignore for whatever reason. You may want to read the scheduler docs: http://docs.ganttproject.biz/scheduler.html
