### ISSUE TITLE
Does not run when executable (Win32) path includes "+"

### ISSUE THREAD

**Issue by ddwp99** [bardsoftware/ganttproject#1400]
The Win32 executable does not run when copied to a path name including the "+" character.  May have something to do with how JRE handle paths.

For example,
"C:\Guy\Tools\ganttproject-2.8.4-r2134\ganttproject.exe" runs properly, but not "C:\Guy\+Tools\ganttproject-2.8.4-r2134\ganttproject.exe" .

This is not a major issue, but may leave some novice users scratching their heads.

**Comment by dbarashev** [comment]
@ddwp99 are you closing this issue because it is resolved now? Frankly, we didn't do anything special about it.

**Comment by ddwp99** [comment]
@dbarashev, I feel like this may have more to do with how the run time environment handles execution paths, and less to do with the integrity of the code itself. The portable users can be made aware of this issue, say in a readme file or something; but the general users who use the installer defaults should be fine. What do you think?

**Comment by dbarashev** [comment]
@ddwp99 can't say for sure what is the reason because I didn't try and don't know what exactly goes wrong. But does it matter from the user perspective? If you install GanttProject in a directory with '+' then you can't run it, whatever is the reason. This issue should be fixed or at least kept open.
