### ISSUE TITLE
Can't seem to modify GUI

### ISSUE THREAD

**Issue by PedroLoures** [bardsoftware/ganttproject#1438]
I'm using IntelliJ with this project and I'm particularly new to Java. I have found most of the stuff that is rendered but I can't seem to understand where do I see it or where to make small changes in the project - want to add some combo boxes for filtering and add some columns and such according to my needs.

But I have been looking into the render and paint functions, they seem to use awt, but not only I can't seem to make them work with the GUI preview from Idea (prob cuz they are not a form), but I also can't grasp where EXACTLY am I supposed to add my stuff.

Can someone give me some pointers on this?

**Comment by dbarashev** [comment]
GanttProject is a complex piece of software and I don't think that you're going to have fun hacking it given that you are new to Java desktop technologies. In particular, nobody can tell you where EXACTLY you are supposed to add anything because it is you who has the idea of changes in mind and only you know where you are going to change code.

All that said, you may want to look at [this pull request](https://github.com/bardsoftware/ganttproject/pull/1419) for the purpose of adding columns to task and resource tables. It may server as a starting point.

**Comment by PedroLoures** [comment]
Well, the fact that I'm new to Java may make it not that fun, but I want to learn. Going to check that pull request because it seem to help me a bit.

Let me explain a bit what I intend to do:
Add some combo boxes on top of the Gantt Table so that I can filter all data by that and refresh:
Like check what tasks are due to a period where I'm going to be on vacation.
Or all tasks that someone is responsible.
All tasks that are late (EndDate > CurrentDate).

I want to be able to also sum those filters and save also the applied filters, so when I get back it already sorts it out.

Also add a checkbox column to tell which data I want to export from the data left after the filters are applied.

That is basically what I want to do. But for that to even begin, I need to know where to add a column - that pull request is telling me how - though where to do a draw function to add before the Gantt Table I still got no clue.
