### ISSUE TITLE
Task and resources table empty after CSV import

### ISSUE THREAD

**Issue by Aannor** [bardsoftware/ganttproject#1500]
What steps will reproduce the problem?
1. Open sample project HouseBuildingSample.gan
2. Export it to CSV
3. Restart GanttProject, open HouseBuildingSample again
4. Import CSV file produced at step 2

Result: task table becomes empty while tasks and resources still visible on the charts.

What version of the product are you using? On what operating system?
GanttProject 2.8.6 Pilsen (build 2231) (standalone version), Windows 10 Enterprise 64-bit, Java 8.0.1510.12

Workaround found:
Open old backup version and new faulty version of project in notepad and copy over newly inserted resource lines of code to backup, save as newest version. Open in GanttProject. (The <view> parts of code seemed to be missing in faulty version)

**Comment by dbarashev** [comment]
I took the liberty to update the issue because it isnto reproducible with arbitrary CSV files or projects. It requires to import CSV back into the project where it was exported from.

Let me also notice that CSV import is not supposed to update anything existing. It adds new tasks and resources, with the only option to merge resources by either id, name or email.
