### ISSUE TITLE
GanttProject won't start if there is malformed webdav record in the options file

### ISSUE THREAD

**Issue by derarnold** [bardsoftware/ganttproject#1533]
[ganttproject-20180424131039.log](https://github.com/bardsoftware/ganttproject/files/1942503/ganttproject-20180424131039.log)
I create a webdav server and load the .gan from there. I can not save the file again and when I try to start GP, it hangs :(

**Comment by dbarashev** [comment]
Thanks for reporting! To fix the issue you can just remove settings file from your home folder - `rm /home/oliver/.ganttproject`  -- or open it in any text editor and remove everything between tags 
```
<files>
</files>
```

**Comment by derarnold** [comment]
Hi bgarashev. 
Thanks for the fast reply. I did that, so I can continue working. 
Nevertheless your fine feature - to open and use the .gan directly from the webdav server - does not work :( Since it is sooo easy to collaborate with my team using webdav (no hustle opening and saving the file on the server), it would be nice if you can fix this. 
Can I help?
Oliver

**Comment by dbarashev** [comment]
Well,WebDAV does work, at least in my tests when it is set up properly and has no issues on the server side (I just have checked it with third-party piblic WebDAV service both for reading and writing).

This particular bug is not related to WebDAV per se, it is related to reading a list of recently opened files. It failes when it meets malformed record and I can't say for sure what exactly could be the reason of malformed record in that list. This bug will be fixed in the next update.

**Comment by derarnold** [comment]
Perfect! I wanted to try the fix and build GP on my Ubunru 18.04 (Beta) machine. Unfortunately I was not able to fire the gradle updateLibs command. It somehow was not able to download the plugins :( So I gave up. Can you attach the binary of this Branch? If you want I can test it and confirm if the fix is working.
