### ISSUE TITLE
Alignment problem

### ISSUE THREAD

**Issue by michmichyo** [bardsoftware/ganttproject#1615]
Hello,

I just downloaded the latest version of ganttproject and I have the same problem as expressed in ticket #1415 .
I use the free version.

Thanks, good luck, and congrats for the wonderful job!
Best,

Yoram

**Comment by michmichyo** [comment]
I just closed and opened the program again and it is now aligned.
In the case I can reproduce the problem, I will update here.

**Comment by DanL123** [comment]
Saw the same, manged to recreate it. 

1. Start with creating a project with numerous tasks and sub tasks. Save it.
2. Close the project, reopen (i did many times, but dont think is necessary)
3. Move to the resources tab and enter some resources / people. Save it, close the app. *
4. Re-open the app, load the plan - you notice that you are now in the resources pane.
5. select the gantt chart - initially, the page is aligned correctly. Now grab the gantt chart with the "little hand" and drag it around - the task row vs gantt alignment jumps-out of alignment by 1 row.

* you may need to make sure that the gantt was big enough so that you can save the project so the first task is off the screen.

I'm on 2.8.10 pilsen build 2363 and Java v8 update 201 (15.1.2019)

Thanks,
Dan

**Comment by DanL123** [comment]
Ps. Workaround is to select the gantt view, edit it in some minor way, save it while in the gantt view, close & re-open. :-D

**Comment by dbarashev** [comment]
Closing in favor of #1798
