### ISSUE TITLE
not running with openjdk

### ISSUE THREAD

**Issue by magithub1** [bardsoftware/ganttproject#1660]

**Comment by magithub1** [comment]
Hallo, 
ganttproject is an great think! Thank you!
But oracle isn't it. On my System java is well installed
----
java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
---
But gantproject.exe means I must install at least java 7 and it show me the oracle download page. Unfortunately oracle java is no more a free software :-( 
Why ganttproject no running with openjdk?

with regards

**Comment by JvHummel** [comment]
Hi. Same here, using GanttProject 2.8.10.

`M:\>java -version
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)`

As a work-around:
In the Program Files folder of GanttProject, launch ganttproject.bat
This successfully runs GanttProject.

**Comment by whdxwym** [comment]
I use Amazon Corretto, meet the same issue, and the work-around method works, too.

**Comment by dbarashev** [comment]
GanttProject runs fine with any Java Runtime provided that Java Runtime vendor updates Windows Registry so that the runtime could be found or java.exe is available in the PATH. Unfortunately currently there is some sort of turbulence in the world of Java Runtimes and there is no standard way of detecting if Java Runtime is installed or not. That's why the launcher (ganttproject.exe), which is generated by launch4j, can't find third-party runtimes and that's why we still recommend using Java 8 from Oracle which is still free. 
If you really want to use JRE from other vendors, please make sure that `java` is in your PATH and you can run it in the command prompt and follow the workaround described above.
