### ISSUE TITLE
Get rid of OSXAdapter

### ISSUE THREAD

**Issue by juananpe** [bardsoftware/ganttproject#1712]
Can we get rid of the [OSXAdapter](https://github.com/bardsoftware/ganttproject/blob/master/ganttproject/src/net/sourceforge/ganttproject/OSXAdapter.java) class? 

[com.apple.eawt.Application.addApplicationListener](https://github.com/bardsoftware/ganttproject/blob/master/ganttproject/src/net/sourceforge/ganttproject/OSXAdapter.java#L110) is not working anymore (it was deprecated in previous JDK versions)  and the rest of the methods are now included in java.awt.Desktop as of JDK 9 ([macOS-specific features have been removed in JDK 9](https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-97C1D0BB-D5D3-4CAD-B17D-03A87A0AAF3B))

If accepted, I can add a PR to this issue but first I would like to know if in master version you are able to show the menubar of GanttProject integrated in macOS system bar (not in my case, even after calling `System.setProperty("apple.laf.useScreenMenuBar", "true"); `

In fact, I think that the setupSystemProperties method from OSXAdapter should be preserved... not sure.

Moreover, the handleOpenFile from OSXAdapter is supposed to  handle the case when a file in the Finder is dropped onto the app but it is not working anymore (without any changes to the master version). To double check it, I've also downloaded the 2.8.10 version, tried to drag&drop a .gan file to it with no luck (nothing happens).

Finally, I'd like to know if this kind of questions are better posted to the forum in help.ganttproject.biz or here... 

Thanks!

**Comment by dbarashev** [comment]
Hola Juanan,
sure, if there is a working replacement for OSXAdapter, we should upgrade it. 

I will check how does it work on my old Mac :)

**Comment by juananpe** [comment]
[This call ](https://github.com/bardsoftware/ganttproject/blob/86c00304004eae445247a8642551d36bc5a88420/ganttproject/src/net/sourceforge/ganttproject/GanttProject.java#L672) to OSXAdapter.setupSystemProperties() is too late  to be effective (the menu items are not integrated in the Apple system's menu. We should call it earlier (see my suggestion at the end of this comment)

Instead of setting this property to change the name of the application in the system's About menu:
    System.setProperty("com.apple.mrj.application.apple.menu.about.name", "GanttProject");
I think that we should use 
    System.setProperty("apple.awt.application.name", "GanttProject");

My suggestion would be to remove OSXAdaptor (and the calls from GanttProject.java) and move the needed setProperty calls to a class run earlier (like MainApplication.java ?)

```
static {
    System.setProperty("apple.awt.graphics.EnableQ2DX", "true");
    System.setProperty("apple.laf.useScreenMenuBar", "true");
    System.setProperty("apple.awt.application.name", "GanttProject");
  }
```
Don't know if we can set those properties unconditionally without breaking anything in non-OSX systems (I hope so! :)

Here is my PoC: https://github.com/juananpe/ganttproject/commit/65bd68cb898300200fb3b96f75ca4db7afdabfa1
If agree, I will add a PR.

**Comment by dbarashev** [comment]
We can pass system properties in the launcher scripts/binaries. [GanttProject launcher which is produced by jpackager](https://github.com/bardsoftware/ganttproject/blob/master/build-bin/package-mac.sh) already works this way. I tried GP 3.0 app, it worked fine on my old Mac OSX 10.9. Didn't try on the modern macOS though.

**Comment by juananpe** [comment]
Yep, didn't know about that GanttProject launcher :-O 
It took me a while to figure out how to run it from the command line. It seems that it is not documented [here](http://docs.ganttproject.biz/development/build/). I used the following command:

`./gradlew -b package.gradle build`

and a zip was created in /build/dist. Unzipped it, executed the GanttProject.app and it worked like a charm. It seems that, as you mentioned, the needed properties for integrating GP in macOS menus are OK just passing them [as JVM arguments](https://github.com/bardsoftware/ganttproject/blob/master/build-bin/package-mac.sh#L51)

So no need to use the OSXAdapter class at all, that's why I have proposed a PR for its removal.

PD: any hint about any upcoming new [GanttProject release](http://docs.ganttproject.biz/releases/)? It has been a while since last one :)

**Comment by dbarashev** [comment]
`package.gradle` may work but I currently use something like

```
gradle distbin
build-bin/package-mac.sh build ganttproject-builder/dist-bin 2.99
```

This works fine with any JDK 11 with bundled JavaFX (e.g. from Azul or BellSoft Liberica)

> any hint about any upcoming new GanttProject release

I am working on the packaging bits of the maintenance release 2.8.11. macOS packaging is a pain (as usually). Distro with the bundled JRE will most likely be the default option (~100Mb download, ~180Mb on disk). However, the existing users may want to use their existing Java Runtime. I recently had some success with [Platypus](https://sveinbjorn.org/platypus) which just executes a shell script. So the remaining part is to update the shell script so that it searched executable `java` everywhere: first in PATH, then in JAVA_HOME, then using /usr/libexec/java_home, then in all possible locations which I am aware of, and finally, if it fails to find executable `java`, make it showing an alert popup with some instructions for the user. 

If you can assist with any of these, please let me know :)

**Comment by juananpe** [comment]
Should we add the "Fix committed to the repository" label to this issue? I'd do it myself, but I don't have enough rights, it seems.

**Comment by dbarashev** [comment]
This label is optional. Its primary purpose is to indicate that some user-visible bug is known, is open in the latest stable version, the fix is ready and will be published in the next maintenance update. I also use it for writing release notes and for tagging issues which were closed in the maintenance update. 

Internal task in `master` branch (which is work in progress anyway) may leave without these tags.
