### ISSUE TITLE
Calendar per Task or Ressources

### ISSUE THREAD

**Issue by FrankyCHAMBERS** [bardsoftware/ganttproject#1774]
I am actually testing ganttproject, and there is one thing I am missing :
the possibility to link a calendar to a task as whith ProjectLibre.
Is this a modification you could consider ?
Regards.

**Comment by dbarashev** [comment]
Do you men what is described in issue #760 or anything beyond that?

**Comment by dbarashev** [comment]
So, the request to add resource calendars is addressed in issue #668
Task calendar is addressed, up to some extent, in issue #760. That issue says about weekends only, but it is likely that, if fixed, it will just add to the individual tasks the same calendar features which are available for the whole project.

I am closing this ticket because it addresses different issues and looks a little bit vague.
