### ISSUE TITLE
Print is not work on Mac

### ISSUE THREAD

**Issue by higamma** [bardsoftware/ganttproject#2048]
I can't print on macOS.
When I press print button, then spring wait cursor is available.

https://user-images.githubusercontent.com/166818/157776798-820123ec-9987-4fed-8e94-e3c6b2f83293.mov

**Comment by dbarashev** [comment]
Can you please test if the update 3222 fixes this issue? 
You can download a ZIP file from this link https://www.dropbox.com/s/1v4gdedarllfhuz/update-3222.zip?dl=1

You need to unpack this ZIP archive into `.ganttproject.d/updates` folder in _your user home directory_ so that the result file structure looked like this:

```
.ganttproject.d/updates/
└── update-3222
    ├── ganttproject
    └── VERSION
.... other updates
``` 

Make sure that all the previous updates suggested by the Updater are installed.
GP 3.2 is expected to show version 3222 in the About dialog.

**Comment by higamma** [comment]
Sorry, I miss to check the bugfix.
Bud anyway, still print function is not to work.
[ganttproject_print_errorlog.txt](https://github.com/bardsoftware/ganttproject/files/8320006/ganttproject_print_errorlog.txt)

https://user-images.githubusercontent.com/166818/159385987-ad0eb4d3-9168-460e-9800-bdad02cb0361.mov

**Comment by dbarashev** [comment]
Can you please try installing this update https://www.dropbox.com/s/m0uti9e0o3jrpg1/update-3231.zip?dl=1 ?


You need to unpack this ZIP archive into `.ganttproject.d/updates` folder in _your user home directory_ so that the result file structure looked like this:

```
.ganttproject.d/updates/
└── update-3231
    ├── biz.ganttproject.core
    └── VERSION
.... other updates
``` 

Make sure that all the previous updates suggested by the Updater are installed.
GP 3.2 is expected to show version 3231 in the About dialog.

**Comment by higamma** [comment]
It's work! Thanks a lot!!
