### ISSUE TITLE
Notes value placed in a wrong column in the spreadsheet export

### ISSUE THREAD

**Issue by Apfelstruhdl** [bardsoftware/ganttproject#2447]
on windows 11:

Export project to spreadsheet (xls). Open it, see that there the last three columns are "Notes", "Web Link" and "Notes".
Notes of items are found in the "Web Link" column.
Import with a freshly started Ganttproject program returns an error: 

"Something went wrong 

The header contains a duplicate name: "Notes" in [ID, Name, Begin date, End date, Duration, Completion, Cost, Coordinator, Predecessors, Outline number, Resources, Assignments, Task color, Notes, Web Link, Notes]"

**Comment by dbarashev** [comment]
Thanks for reporting! It appears that it is an export configuration issue. There are two "Notes" options in the export settings (Edit > Settings > Spreadsheets). This issue is reproducible when both Notes options are checked, as shown on this screenshot:

![image](https://github.com/bardsoftware/ganttproject/assets/2028330/9d35aac6-6586-4189-a8ea-9ed6ec22a5ba)

Unchecking the _first_ Notes checkbox makes export working as expected:
![image](https://github.com/bardsoftware/ganttproject/assets/2028330/9b11ea7f-af14-4b22-a45e-ca323280d1e7)
