### ISSUE TITLE
Option to hide completed tasks

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bardsoftware/ganttproject#580]
```
Should be possible to hide tasks which are completed.

See also issue #541
```

Original issue reported on code.google.com by `dbarashev` on 4 Sep 2012 at 11:42

**Comment by EtienneBasilik** [comment]
Yes, that would be very useful. Indeed, when tasks are complete, we want to tidy-up the list to have a clear view of what is left to be done. However, we do not want to delete tasks to do that because we want to keep the history. Hiding a task manually would be great. (e.g. right click -> hide; View menu -> Show hidden tasks = Yes/no)

**Comment by kholis** [comment]
I wish this feature is prioritize. 😀

**Comment by dbarashev** [comment]
This filter was added in GP 3.2
