### ISSUE TITLE
baseline not showing up 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bardsoftware/ganttproject#919]
```
I am new to the software. I am trying to add baselines to my tasks without 
success. 
I go to Edit baselines, click Add
type a name for my baseline, press enter
change the desired display colors , click ok
I go back to my Gantt chart and although it seems to have made space for the 
baseline, nothing shows up. I have changed the dates around to display tasks 
completed earlier and later, but nothing shows up. 
Could you please help me? Do you have a step by step tutorial on how to use 
baselines, what do they exactly mean in this context? 
Thank you! 
Version 2.6.5 was used 
```

Original issue reported on code.google.com by `deyranro...@gmail.com` on 21 Apr 2014 at 7:49

**Comment by sslavi** [comment]
Hello,
I have to second the question by Carlos.
I am using 2.7.1 Ostrava Build on a Win7 machine and the baseline button is not there.
There is no baseline button.
Has it been removed for some reason in this version of GanttProject?
Cheers

**Comment by dbarashev** [comment]
Baseline button is there.
![tmp](https://cloud.githubusercontent.com/assets/2028330/15426806/a48454ba-1e99-11e6-8799-cd81a76a0fa4.jpg)

**Comment by sslavi** [comment]
Sir,
I wouldn't lie to you... :)
There is no baseline button in my version of GanttProject (GanttProject 2.7.1 Ostrava build 1924).

![ganttproj](https://cloud.githubusercontent.com/assets/19324257/15429092/550c387a-1e9f-11e6-8183-bc832e8311c7.jpg)

**Comment by sslavi** [comment]
Ok, thanks. Now I understand why I couldn't localize the button - because of the unfortunate translation of the word "baseline" into italian. It was translated as "Stato dell'arte" (State of art), which has a quite foggy meaning in this context. Leaving the word "baseline" might have been a better choice, imho.
![ganttproj](https://cloud.githubusercontent.com/assets/19324257/15430082/082db696-1ea4-11e6-8aee-2c87945becab.jpg)
Anyways, thanks again for the reply this clarification.
That said, the YouTube seem to be very unaware of the baseline option in GanttProject. I am still trying to find out a tutorial about how to use it... ;)
Cheers

**Comment by dbarashev** [comment]
If you have any idea how to make Italian translation better, pls join the translation efforts: 

https://github.com/bardsoftware/ganttproject/blob/wiki/TranslationGuidelines.md
https://crowdin.com/project/ganttproject/it#
